### ISSUE TITLE
InvalidApiVersionError "The version of this extension is not the same. Extension version 0.1.4, Api version: 0.1.1. Please retry the request with the correct version "

### ISSUE THREAD

**Issue by unxavi** [RevenueCat/firestore-revenuecat-purchases#38]
I just installed the extension (0.1.4) and tried out with an iOS App with the SDK 4.10.0 and I get the following error on Firebase

```
InvalidApiVersionError
The version of this extension is not the same. Extension version 0.1.4, Api version: 0.1.1. Please retry the request with the correct version
InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.4, Api version: 0.1.1. Please retry the request with the correct version at Object.exports.validateApiVersion (/workspace/lib/validate-api-version.js:7:15) at /workspace/lib/index.js:49:32 at cloudFunction (/workspace/node_modules/firebase-functions/lib/providers/https.js:50:16) at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:101:17 at processTicksAndRejections (internal/process/task_queues.js:77:11)
Service
ext-firestore-revenuecat-purchases-handler 
```

**Comment by alfondotnet** [comment]
Hi @unxavi 👋 , 

That error got fixed automatically and it's part of an automatic version upgrade system. Our backend defaulted to 0.1.1 and the request quickly got retried with the correct version.

I can see in our database that all of your requests are functioning normally, but thanks for pointing this error out! Agree it's confusing. Will fix.
